name: Docker Build and Push

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get tag name
        id: tag_name
        if: github.event_name == 'release'
        run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | sed 's/refs\/tags\///')

      - name: Determine tag name
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        id: tag_name_from_push
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Set tag name
        id: final_tag_name
        run: echo ::set-output name=FINAL_TAG_NAME::${{ steps.tag_name.outputs.TAG_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bestione/shopwize:${{ github.sha }} .
          docker tag bestione/shopwize:${{ github.sha }} bestione/shopwize:${{ steps.final_tag_name.outputs.FINAL_TAG_NAME }}
          docker tag bestione/shopwize:${{ github.sha }} bestione/shopwize:latest
          docker push bestione/shopwize:${{ github.sha }}
          docker push bestione/shopwize:${{ steps.final_tag_name.outputs.FINAL_TAG_NAME }}
          docker push bestione/shopwize:latest
